apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: java-app
spec:
  containers:
  - name: java-demo
    image: my-image-java
    ports:
    - name: java-port
      containerPort: 3000
